services:
  quizmaker.api:
    image: quizmaker.api
    container_name: quizmaker.api
    build:
      context: .
      dockerfile: QuizMaker.API/Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on: 
      quizmaker.database:
        condition: service_healthy
    ports:
      - "5008:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - quizmaker-network
        
  quizmaker.database:
    image: postgres
    container_name: quizmaker.database
    environment:
      POSTGRES_DB: quizmaker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - quizmaker-network
    restart: unless-stopped
    healthcheck :
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval : 5s
      timeout : 5s
      retries : 5
 
networks:
  quizmaker-network:
    driver: bridge

volumes:
    postgres:

